language: cpp

env:
    global:
        - LINUX_DIST=trusty
        - BUILD_TESTS=true
        - COVERAGE=false
        - GEN_DOC=false

sudo: true
os: linux
dist: trusty
compiler:
    - gcc
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - cmake
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - "[ $CXX = g++ ] && export CXX=g++-8 || true"

script:
    - mkdir -p bin
    - cmake CMakeLists.txt
    - make
    - ./bin/frameworkUT
    - ./bin/keyboardmasterUT


after_success:
    - echo "Congratulations!"
